const swaggerAutogen = require('swagger-autogen')();

const doc = {
    info: {
        version: "1.0.0",
        title: "Noroff EP e-commerce API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module.",
    },
    host: "localhost:3001",

    definitions: {
        Product: {
            $id: 1,
            $name: "Swagger Product",
            $description: "Swagger Description",
            $price: 10,
            $quantity: 1,
            $imageUrl: "http://swagger.com/product-image.png",
            $brand: "Swagger Brand",
            $category: "Swagger Category",
        },
        User: {
            $id: 1,
            $firstName: "John",
            $lastName: "Doe",
            $username: "johndoe",
            $email: "john.doe@example.com",
            $address: "123 Main St",
            $phone: "1234567890",
            $roleId: 2,
            $membershipId: 1,
        },
    },
};

const outputFile = './swagger-output.json';
const endpointsFiles = ['./app.js'];

swaggerAutogen(outputFile, endpointsFiles, doc);